name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - name: Build Nix
        run: nix build .\#devShell.x86_64-linux
      - name: Typecheck
        if: success() || failure()  # Means that we run all steps even if one fails.
        run: nix .\#devShell.x86_64-linux --command make typecheck
      - name: Test
        if: success() || failure()
        run: nix .\#devShell.x86_64-linux --command make test
      - name: Lint
        if: success() || failure()
        run: nix .\#devShell.x86_64-linux --command make lintcheck
