name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - name: Build Nix
        run: nix build .\#devShell.x86_64-linux
